name: Django Tests Automation with GitHub Action

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Testing
        run: |
          python manage.py test
  analyse-sonarcloud:
    # name: SonarCloud Trigger
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Clone Repository
    #     uses: actions/checkout@v2
    #   - name: Analyze with SonarCloud
    #     uses: sonarsource/sonarcloud-github-action@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: philips-software/sonar-scanner-action@4.6.2.2472
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          projectName: opeyemi19
          projectKey: Opeyemi19_django_test_github_action
          baseDir: .
          url: https://sonarcloud.io/
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    #   with:
    #     # Disabling shallow clone is recommended for improving relevancy of reporting
    #     fetch-depth: 0
    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   with:
    #     args: >
    #       -Dsonar.organization=Opeyemi19
    #       -Dsonar.projectKey=Opeyemi19_django_test_github_action
    #       -Dsonar.python.coverage.reportPaths=coverage.xml
    #       -Dsonar.sources=lib/
    #       -Dsonar.test.exclusions=tests/**
    #       -Dsonar.tests=tests/
    #       -Dsonar.verbose=true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}